#! /usr/bin/env bash

cleanup()
# example cleanup function
{
  pkill -P $$
}

control_c()
# run if user hits control-c
{
  echo -en "\n*** Ouch! Exiting ***\n"
  cleanup
  exit $?
}

# trap keyboard interrupt (control-c)
trap control_c INT

#trap "exit" SIGINT SIGTERM

echo server_starting
cd node_middleware && yarn run server $1 $2 &

# Then, we start the dev server
#echo dev
cd vue_frontend && yarn run dev

# When the node server dies, we kill this process.
cleanup
# echo starting
# echo done
