apiVersion: v1
kind: Service
metadata:
  name: tufts-tamu
  labels:
    app: tufts-tamu
spec:
  loadBalancerIP: 10.108.5.97
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tufts-tamu
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tufts-tamu-deployment
  labels:
    app: tufts-tamu-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tufts-tamu
  template:
    metadata:
      name: tufts-tamu
      labels:
        app: tufts-tamu
    spec:
      restartPolicy: Always
      containers:
    # TAMU TA2
      - name: tamu-ta2
        imagePullPolicy: Always
        image: jhfjhfj1/tamuta2:latest
        volumeMounts:
          - name: input-vol
            mountPath: /input
            readOnly: true
          - name: output-vol
            mountPath: /output
            readOnly: false
        ports:
        - containerPort: 45042
          hostPort: 45042
        resources:
          requests:
            memory: 1Gi
            cpu: 1
        env:
        - name: D3MTIMEOUT
          value: "60"
        - name: D3MINPUTDIR
          value: /input
        - name: D3MOUTPUTDIR
          value: /output
        - name: D3MRUN
          value: ta2ta3
    # TUFTS TA3
      - name: tufts-ta3
        imagePullPolicy: Always
        image: registry.datadrivendiscovery.org/fheimerl/tuftsgtwiscta3:latest
        command: [./ta3_search]
        args:
          - static/config_files/eval_mode/baseball.json
        volumeMounts:
          - name: input-vol
            mountPath: /input
            readOnly: true
          - name: output-vol
            mountPath: /output
            readOnly: false
        ports:
        - name:  http
          containerPort: 8080
        resources:
          requests:
            memory: 1Gi
            cpu: 1
        env:
        - name: TA2_PORT
          value: "45042"
      imagePullSecrets:
      - name: regcred3
      volumes:
      - name: input-vol
        hostPath:
          path: /opt/datasets/seed_datasets_current/
          type: Directory
      - name: output-vol
        persistentVolumeClaim:
          claimName: eval-output-pv-claim
