apiVersion: v1
kind: Service
metadata:
  name: tufts-testing
  labels:
    app: tufts-testing
spec:
  loadBalancerIP: 10.108.5.99
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: tufts-testing
---
apiVersion: v1
kind: Pod
metadata:
  name: tufts-testing
  labels:
    app: tufts-testing
spec:
  restartPolicy: Always
  containers:
# MIT-FEATURELABS TA2
  - name: ucb-ta2
    imagePullPolicy: Always
    image: registry.datadrivendiscovery.org/fheimerl/tuftsgtwiscta3/ucb-aika:ta2
    volumeMounts:
      - name: shared-memory
        mountPath: /dev/shm
      - name: static-data
        mountPath: /volumes
        readOnly: true
      - name: input-vol
        mountPath: /input
        readOnly: true
      - name: output-vol
        mountPath: /output
        readOnly: false
    ports:
    - containerPort: 45042
      hostPort: 45042
    resources:
      requests:
        memory: 30Gi
        cpu: 4
    env:
    - name: D3MTIMEOUT
      value: "60"
    - name: D3MINPUTDIR
      value: /input
    - name: D3MOUTPUTDIR
      value: /output
    - name: D3MRUN
      value: ta2ta3
    - name: D3MCPU
      value: "4"
    - name: D3MRAM
      value: "30Gi"
# TUFTS TA3
  - name: tufts-ta3
    imagePullPolicy: Always
    image: registry.datadrivendiscovery.org/fheimerl/tuftsgtwiscta3:latest
    command: [./ta3_search]
    args:
#      - dataset:popularkids
      - dataset:__direct__
    volumeMounts:
      - name: input-vol
        mountPath: /input
        readOnly: true
      - name: output-vol
        mountPath: /output
        readOnly: false
    ports:
    - name:  http
      containerPort: 8080
    resources:
      requests:
        # that's what we've been testing on:
        memory: 16Gi
        cpu: 2
    env:
    - name: TA2_PORT
      value: "45042"
  imagePullSecrets:
  - name: regcred3
  volumes:
  - name: static-data
    hostPath:
      path: /opt/static_files/
      type: Directory
  - name: input-vol
    hostPath:
      path: /opt/datasets/seed_datasets_current/LL0_1100_popularkids/
      type: Directory
  - name: output-vol
    persistentVolumeClaim:
      claimName: eval-output-pv-claim
  - name: shared-memory
    emptyDir:
      medium: Memory
